#Port
server:
  port: 8091
debug: true
spring:
  #Monogo DB connection
  data:
    mongodb:
      database: sample_mflix
      uri: mongodb+srv://m220student:m220password@m220.dp7vh.mongodb.net/sample_mflix?retryWrites=true&w=majority
  rabbitmq:
    port: 5672
    listener:
      simple:
        acknowledge-mode: manual

layering-cache:
  redis:
    host: localhost
    port: 6379
    serializer: com.github.xiaolyuh.redis.serializer.JacksonRedisSerializer

resilience4j:
  retry:
    retry-aspect-order: 399
    backends:
      retryA:
        maxRetryAttempts: 5
        waitDuration: 500
        exponentialBackoffMultipliter: 1.1
        retryException:
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      cbA:
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitInterval: 5000
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
    circuit-breaker-aspect-order: 400

